# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled=true

[character]
success_symbol = "[/>](bold green) "
error_symbol = "[/>](bold red) "

